-- ============================================================
-- AARBI CLOTHING — Migration 0001: create `products` CRUD table
-- Ye file supabase/migrations/ me hai. GitHub integration ise:
--   * production branch (main) merge par deploy karta hai
--   * sirf UNA bar chalata hai (schema_migrations track karta hai)
-- Aap chaaho toh isko SQL Editor me bhi chala sakte ho (same script).
-- ============================================================

-- --- Table banayein ---
create table if not exists public.products (
  id         bigint generated by default as identity primary key,
  name       text not null unique,         -- unique (ON CONFLICT ke liye zaroori)
  price      integer not null default 0,   -- PKR
  stock      integer not null default 0,
  category   text not null default 'Other',
  created_at timestamptz not null default now()
);

-- --- Seed data (dashboard me pehle se products dikhein) ---
insert into public.products (name, price, stock, category) values
  ('Classic Cotton T-Shirt',          1200, 25, 'Shirts'),
  ('Men''s Slim Fit Jeans',           2500, 18, 'Pants'),
  ('Female Lawn Shalwar Kameez',      3200, 30, 'Shalwar Kameez'),
  ('Kids T-Shirt Multi-Pack',         1500, 40, 'Kids'),
  ('Leather Formal Shoes',            4500, 12, 'Shoes'),
  ('Elegant Evening Clutch',          1800, 18, 'Purses'),
  ('Classic Denim Overshirt',         2799, 20, 'Shirts'),
  ('Linen Casual Shirt',              2599, 24, 'Shirts'),
  ('Premium Polo Trio',               2299, 30, 'Shirts'),
  ('Regular Cargo Pants',             3399, 18, 'Pants'),
  ('Slim Chino Trousers',             3099, 16, 'Pants'),
  ('Trail Running Sneakers',          4899, 14, 'Shoes'),
  ('Urban Loafer Mules',              3799, 12, 'Shoes'),
  ('Satin Ready-To-Wear Suit',        5999, 12, 'Shalwar Kameez'),
  ('Printed Cotton Kurti',            2299, 32, 'Shalwar Kameez'),
  ('Chiffon Party Kameez',            5299, 16, 'Shalwar Kameez'),
  ('Khaddi Embroidered Suit',         4499, 10, 'Shalwar Kameez'),
  ('Quilted Crossbody Bag',           3799, 20, 'Purses'),
  ('Structured Top-Handle Bag',       4599,  9, 'Purses'),
  ('Satin Block Heels',               2699, 18, 'Heels'),
  ('Open-Toe High Heels',             3499, 11, 'Heels'),
  ('Kids Graphic Tee Set',            1299, 40, 'Kids'),
  ('Kids Denim Overalls',             2199, 22, 'Kids'),
  ('Kids Cartoon Sneakers',           1899, 26, 'Kids'),
  ('Toddler Winter Jacket',           1999, 14, 'Kids'),
  ('Teen Floral Hoodie',              2499, 17, 'Kids')
on conflict (name) do nothing;

-- --- RLS on karein + anon ke liye full CRUD allow karein ---
alter table public.products enable row level security;

create policy "allow all for anon and authenticated"
  on public.products
  for all
  to anon, authenticated
  using (true)
  with check (true);